### ISSUE TITLE
Cannot import model

### ISSUE THREAD

**Issue by constantinpape** [jhennies/pytorch_membrane_net#2]
I cannot import any models because of this line:
/home/pape/Work/software/conda/miniconda3/envs/torch13/lib/python3.7/site-packages/pytorch_tools/piled_unets.py

I would expect this to be
```py
from pytorch_tools.modules import Unet
```
instead of
```py
from pytorch.pytorch_tools.modules import Unet
```

**Comment by jhennies** [comment]
yep it has to be 

from pytorch_tools.modules import Unet

I fixed and commited, I hope I didn't miss any occurences

**Comment by constantinpape** [comment]
Yes, it's fixed.
